sub_db:
    image: hypriot/rpi-mysql
    ports:
        - "3307:3306"
    environment:
        - "MYSQL_ROOT_PASSWORD=cnim"
        - "MYSQL_USER=root"
        - "MYSQL_PASSWORD=cnim"
        - "MYSQL_DATABASE=sub_ai"

sub_server:
    build: ./docker/rpi/
    volumes:
        - ".:/home/subena:rw"
    links:
        - "sub_db:sub_db"
    working_dir: "/home/subena"
    ports:
        - "5007:5000"
    environment:
        - "SUBDB=mysql://root:cnim@192.168.0.117:3307/sub_ai"
